### ISSUE TITLE
훈련장 기능 구현

### ISSUE THREAD

**Issue by fakerdeft** [mtvs-2ndteam/hero-maker#10]
# Issue: 🐵FEATURE

## 🎈Description
스탯 4가지 (체력 / 힘 / 마력 / 무기술) 중 1가지를 플레이어가 선택하여 소폭 상승시킬 수 있다.
스탯 포인트 2 상승

## 🎹Progress
- [x] 체력/힘/마력/무기술 중 한 가지 스탯 포인트 2 상승

## 🪐ETC

**Comment by jisoo9603** [comment]
구현완료
